@startuml
'https://plantuml.com/class-diagram

class system
class input
class application
class d3d
class uiManager

class ui
class callback

system *-- input : contain
system *-- application : contain
system *-- d3d : contanin
system *-- uiManager : contain

ui *-- callback

@enduml