@startuml
'https://plantuml.com/structure

class system
class input
class application
class d3d
diamond dia

system *-- input : contain
system *-- application : contain
system *-- d3d : contanin
@enduml